# Generated by Django 4.2.1 on 2023-06-02 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=400)),
                ('last_active', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_active', models.DateField(auto_now_add=True)),
                ('access_level', models.PositiveIntegerField(verbose_name='Access Level')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtyagent.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('data', models.FileField(upload_to=None)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtyagent.organization')),
            ],
        ),
    ]
