# Generated by Django 4.1 on 2023-06-09 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtyagent', '0002_alter_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='realtyagent.organization'),
            preserve_default=False,
        ),
    ]
